MODEL:
  PRETRAIN_CHOICE: 'finetune'
  PRETRAIN_PATH: 'resnet50_ibn_a_80.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'resnet50_ibn_a'
  NO_MARGIN: True
  DEVICE_ID: ('0')

INPUT:
  SIZE_TRAIN: [280, 280]
  SIZE_TEST: [280, 280]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('veri')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 6
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 80
  BASE_LR: 0.01
  IMS_PER_BATCH: 48
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10

TEST:
  EVAL: True
  IMS_PER_BATCH: 32
  RE_RANKING: True
  RE_RANKING_TRACK: True
  WEIGHT: './logs/veri/resnet50_ibn_a_80.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './output_data/veri'


